### ISSUE TITLE
Readme.md File can be more fascinating 

### ISSUE THREAD

**Issue by Meetjain1** [RituKumari98/imgIN#27]
currently our Readme.md File looking not so good It can be more fascinating with some 3d images along with contributors , code of conduct section etc. @RituKumari98 assign this issue to me I will create it . Thankyou

**Comment by aasthakourav20** [comment]
Hey @RituKumari98 , Kindly assign this task to me under GSSoC'24 .

A README file is essential in any given repository because it serves as the primary source of information about the project. It provides an overview of the project's purpose, how to install and use it, and any necessary prerequisites. Additionally, the README often includes guidelines for contributing, links to documentation, and contact information for the maintainers.

**Comment by iamkanhaiyakumar** [comment]
I've noticed your project lacks a README.md file, crucial for sharing essential project details and fostering collaboration. As a GSSoC 2024 participant, I'm keen on contributing meaningfully. Can you assign me this task? I'm dedicated to crafting a thorough README for the project's benefit. Thanks for considering. Eagerly awaiting your response.

Thank you @RituKumari98
